# Generated by Django 3.1 on 2020-08-16 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type_of',
            field=models.CharField(choices=[('RADIO', 'Радиокнопка'), ('CHECKBOX', 'Чекбокс')], default='RADIO', max_length=8, verbose_name='Выбор варианта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
        ),
    ]
