# Generated by Django 3.1 on 2020-08-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200816_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
