# Generated by Django 3.1 on 2020-08-17 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20200817_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionnaire',
            old_name='questinnaire_text',
            new_name='questionnaire_text',
        ),
    ]
