# Generated by Django 3.1 on 2020-08-17 03:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200817_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
