# Generated by Django 3.1 on 2020-08-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200817_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninquestionnaire',
            name='question',
            field=models.ManyToManyField(to='polls.Question'),
        ),
    ]
