# Generated by Django 3.1 on 2020-08-17 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20200817_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioninquestionnaire',
            name='question',
        ),
        migrations.AddField(
            model_name='questioninquestionnaire',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question', to='polls.question', verbose_name='Вопрос'),
        ),
    ]
